### ISSUE TITLE
mutt: Replace pgp_self_encrypt_as by pgp_default_key?

### ISSUE THREAD

**Issue by ayekat** [ayekat/dotfiles#27]
It appears that the mutt documentation now refers to `pgp_default_key` rather than `pgp_self_encrypt_as`, so I'm not sure if it was deprecated or simply replaced (and thus my self-encryption mechanism no longer works).

Should check and potentially update my `muttrc`.

**Comment by ghost** [comment]
The manpage entry for `pgp_default_key` quotes `The (now deprecated) pgp_self_encrypt_as is an alias for this variable, and should no longer be used.  (PGP only)`, so you should ideally use `pgp_default_key`. This also avoids having to set `pgp_sign_as`, since the value of the latter is filled with the former unless otherwise specified.
(just passing through ;))

**Comment by ayekat** [comment]
Thank you very much for the nudge; 14147946 appears to make it work (I can now read my own mails again).

Closing as fixed.
